# Generated by Django 5.1.2 on 2024-11-04 20:31

import django.db.models.deletion
import xmlrpc.client
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False)),
                ('Obejt', models.CharField(blank=True, max_length=500, null=True)),
                ('debut_action', models.DateTimeField(verbose_name=xmlrpc.client.DateTime)),
                ('echeance', models.DateTimeField(null=True, verbose_name=xmlrpc.client.DateTime)),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.product')),
            ],
        ),
    ]
