# Generated by Django 3.1.7 on 2022-03-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0003_auto_20220327_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_client',
            new_name='id',
        ),
    ]
