# Generated by Django 5.1.2 on 2024-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='qte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='debut_action',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='echeance',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
