# Generated by Django 3.1.7 on 2022-03-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0004_auto_20220327_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='numero',
        ),
    ]
