# Generated by Django 4.0.4 on 2022-08-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0004_alter_commande_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='id_product',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
    ]
