# Generated by Django 3.1.7 on 2022-04-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0005_remove_client_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_command',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='id_product',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
