# Generated by Django 3.1.7 on 2022-04-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0009_auto_20220405_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='qte',
        ),
    ]
