# Generated by Django 3.1.7 on 2022-04-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0010_remove_commande_qte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_command',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_product',
        ),
        migrations.AddField(
            model_name='commande',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='qte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
