# Generated by Django 3.1.7 on 2022-04-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0011_auto_20220405_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='commande',
            name='id_command',
            field=models.AutoField(default=' ', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id_product',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client'),
        ),
    ]
