# Generated by Django 3.1.7 on 2022-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0012_auto_20220405_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='id_command',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
    ]
