# pull official base image
FROM python:3.9.6-alpine


# set environment variables
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
# set work directory
RUN mkdir CRM_CNCT
WORKDIR /CRM_CNCT
COPY ./CRM_CNCT /CRM_CNCT/
EXPOSE 8000
CMD cd /CRM_CNCT && python manage.py runserver 0.0.0.0:8000