# pull official base image
FROM python:3.9.6-alpine



# set environment variables
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
# set work directory
RUN mkdir /app
WORKDIR /app
COPY ./app /app/

RUN adduser -D user
USER user