# Generated by Django 4.0.4 on 2022-08-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0005_remove_product_id_product_id_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='id',
        ),
    ]
