# Generated by Django 4.0.4 on 2022-08-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0006_rename_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='id_command',
            new_name='id',
        ),
    ]
