# Generated by Django 4.0.4 on 2022-08-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0009_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='qte',
            field=models.IntegerField(default='0'),
        ),
    ]
