# Generated by Django 4.0.4 on 2022-08-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0010_commande_qte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
