# Generated by Django 4.0.4 on 2022-08-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommercialApp', '0011_delete_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False)),
                ('qte', models.IntegerField(default='0')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.product')),
            ],
        ),
    ]
