# Generated by Django 5.1.2 on 2024-11-01 20:27

import django.db.models.deletion
import django.forms.fields
import xmlrpc.client
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommercialApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='segment_marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_segment', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='ActionCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_action', models.CharField(max_length=20)),
                ('CA_esperer', models.IntegerField(blank=True, null=True)),
                ('Cout_action', models.IntegerField(blank=True, null=True)),
                ('But_action', models.CharField(max_length=55)),
                ('debut_action', models.DateTimeField(verbose_name=xmlrpc.client.DateTime)),
                ('echeance', models.DateTimeField(null=True, verbose_name=xmlrpc.client.DateTime)),
                ('completed', models.BooleanField(default=False)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppelTelephonique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(verbose_name=xmlrpc.client.DateTime)),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Opportinite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_opportunite', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=10)),
                ('ca_estime', models.BigIntegerField(blank=True, null=True)),
                ('ca_final', models.BigIntegerField(blank=True, null=True)),
                ('devise', models.CharField(choices=[('dinars', 'dinars'), ('euro', 'euro'), ('dollar', 'dollar')], default=1, max_length=20)),
                ('phase_de_vente', models.CharField(choices=[('en cours', 'en cours'), ('A venir', 'A venir'), ('En négociation', 'En négociation'), ('Abandonnée', 'Abandonnée'), ('gagnée', 'gagnée'), ('perdue', 'perdue')], default=1, max_length=20)),
                ('date_signature', models.DateField(verbose_name=django.forms.fields.DateField)),
                ('document_concernee', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
                ('commercial', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('date_RendezVous', models.DateTimeField(null=True, verbose_name=xmlrpc.client.DateTime)),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
            ],
        ),
    ]
