# Generated by Django 3.1.7 on 2022-04-21 20:54

from django.db import migrations, models
import django.db.models.deletion
import xmlrpc.client


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommercialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCommercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_action', models.CharField(max_length=20)),
                ('CA_esperer', models.IntegerField(blank=True, null=True)),
                ('Cout_action', models.IntegerField(blank=True, null=True)),
                ('But_action', models.CharField(max_length=55)),
                ('debut_action', models.DateTimeField(verbose_name=xmlrpc.client.DateTime)),
                ('echeance', models.DateTimeField(null=True, verbose_name=xmlrpc.client.DateTime)),
            ],
        ),
        migrations.CreateModel(
            name='rendez_vous',
            fields=[
                ('id', models.IntegerField(auto_created=True, default='1', primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=255)),
                ('date_RendezVous', models.DateTimeField(null=True, verbose_name=xmlrpc.client.DateTime)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='AppelTelephonique',
            fields=[
                ('id', models.IntegerField(auto_created=True, default='1', primary_key=True, serialize=False)),
                ('datetime', models.DateField(verbose_name=xmlrpc.client.DateTime)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
            ],
        ),
    ]
