# Generated by Django 3.1.7 on 2022-04-05 22:00

import builtins
from django.db import migrations, models
import django.db.models.deletion
import xmlrpc.client


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommercialApp', '0012_auto_20220405_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='rendez_vous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('date_RendezVous', models.DateTimeField(default=builtins.any, verbose_name=xmlrpc.client.DateTime)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='AppelTelephonique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=builtins.any, verbose_name=xmlrpc.client.DateTime)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommercialApp.client')),
            ],
        ),
    ]
