# Generated by Django 5.1.2 on 2024-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncommercial',
            name='commercial',
            field=models.CharField(choices=[('Colonel Nizar', 'colonel Nizar'), ('Ikram', 'Adm/Chef Ikram '), ('Cne Radhouen', 'Cne Radhouen'), ('Lt Sofienne', 'selected>Lt Sofienne'), ('Adj/C Brahim', 'Adj/C Brahim '), ('Adj/M Chabchoub', 'Adj/M Chabchoub'), ('Chef Imed', 'Sgt/C Imed ')], default=1, max_length=20),
        ),
    ]
