# Generated by Django 3.1.7 on 2022-04-09 15:34

from django.db import migrations, models
import xmlrpc.client


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeltelephonique',
            name='datetime',
            field=models.DateField(verbose_name=xmlrpc.client.DateTime),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='date_RendezVous',
            field=models.DateTimeField(verbose_name=xmlrpc.client.DateTime),
        ),
    ]
