# Generated by Django 5.1.2 on 2024-11-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0002_alter_actioncommercial_commercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportinite',
            name='nom_opportunite',
        ),
        migrations.AlterField(
            model_name='actioncommercial',
            name='commercial',
            field=models.CharField(choices=[('Colonel Nizar', 'Colonel Nizar'), ('Ikram', 'Adm/Chef Ikram'), ('Cne Radhouen', 'Cne Radhouen'), ('Lt Sofienne', 'Lt Sofienne'), ('Adj/C Brahim', 'Adj/C Brahim'), ('Adj/M Chabchoub', 'Adj/M Chabchoub'), ('Chef Imed', 'Sgt/C Imed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actioncommercial',
            name='debut_action',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actioncommercial',
            name='echeance',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appeltelephonique',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='opportinite',
            name='commercial',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportinite',
            name='date_signature',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opportinite',
            name='devise',
            field=models.CharField(choices=[('dinars', 'dinars'), ('euro', 'euro'), ('dollar', 'dollar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opportinite',
            name='phase_de_vente',
            field=models.CharField(choices=[('en cours', 'en cours'), ('A venir', 'A venir'), ('En négociation', 'En négociation'), ('Abandonnée', 'Abandonnée'), ('gagnée', 'gagnée'), ('perdue', 'perdue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='date_RendezVous',
            field=models.DateTimeField(null=True),
        ),
    ]
