# Generated by Django 3.1.7 on 2022-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0002_auto_20220409_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='id_rdv',
            field=models.IntegerField(auto_created=True, default='1'),
        ),
    ]
