# Generated by Django 5.1.2 on 2024-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0003_remove_opportinite_nom_opportunite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportinite',
            name='document_concernee',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
