# Generated by Django 3.1.7 on 2022-04-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0003_rendez_vous_id_rdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendez_vous',
            name='id_rdv',
        ),
    ]
