# Generated by Django 3.1.7 on 2022-04-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0004_remove_rendez_vous_id_rdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='id',
            field=models.IntegerField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
    ]
