# Generated by Django 4.0.4 on 2022-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0004_actioncommercial_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
