# Generated by Django 3.1.7 on 2022-04-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0005_auto_20220409_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeltelephonique',
            name='id',
            field=models.IntegerField(auto_created=True, default='1', primary_key=True, serialize=False),
        ),
    ]
