# Generated by Django 3.1.7 on 2022-04-16 11:39

from django.db import migrations, models
import xmlrpc.client


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0006_auto_20220410_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='date_RendezVous',
            field=models.DateTimeField(null=True, verbose_name=xmlrpc.client.DateTime),
        ),
    ]
