# Generated by Django 4.0.4 on 2022-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0009_remove_opportinite_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportinite',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
