# Generated by Django 4.0.4 on 2022-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0006_opportinite_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportinite',
            name='phase_de_vente',
            field=models.CharField(choices=[('en cours', 'en cours'), ('A venir', 'A venir'), ('3', 'En négociation'), ('4', 'Abandonnée'), ('5', 'gagnée'), ('6', 'perdue')], default=1, max_length=20),
        ),
    ]
