# Generated by Django 4.0.4 on 2022-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0007_alter_opportinite_phase_de_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportinite',
            name='devise',
            field=models.CharField(choices=[('dinars', 'dinars'), ('euro', 'euro'), ('dollar', 'dollar')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='opportinite',
            name='phase_de_vente',
            field=models.CharField(choices=[('en cours', 'en cours'), ('A venir', 'A venir'), ('En négociation', 'En négociation'), ('Abandonnée', 'Abandonnée'), ('gagnée', 'gagnée'), ('perdue', 'perdue')], default=1, max_length=20),
        ),
    ]
