# Generated by Django 4.0.4 on 2022-09-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activités', '0008_alter_opportinite_devise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportinite',
            name='completed',
        ),
    ]
